window.KEYCHAINS = [
  {
    id: 1,
    name: "Chonky the Octopus",
    tagline: "The unfazable pronoic",
    image: "./OPS.jpg",
    shopUrl: "https://www.etsy.com/listing/4452750677/cute-octopus-keychain-mini-keychain?ref=related-4&pro=1&logging_key=7785eef5c28b3ed894cc7bcd6f16b3782224d592%3A4452750677",
    color: "#42c79d",
    personality:
      "Chonky spends his days playing with his fish friends and exploring caves",
    favFood: "Pringles",
    hobby: "Cloud Watching",
    categories: ["animals"],
  },
  {
    id: 2,
    name: "Pip the Penguin",
    tagline: "The Tiny Skater",
    image: "PIP",
    shopUrl: "https://yourshop.com/products/pip",
    color: "#9fd2ff",
    personality:
      "Pip glides across icy counters and insists every day is a rink day. Quietly competitive, loudly cute.",
    favFood: "Vanilla wafers",
    hobby: "Ice sliding",
    categories: ["animals", "sports", "ocean"],
  },
  {
    id: 3,
    name: "Kiko the Koala",
    tagline: "The Cozy Daydreamer",
    image: "KIK",
    shopUrl: "https://yourshop.com/products/kiko",
    color: "#c8d2c0",
    personality:
      "Kiko naps between snack breaks and writes little notes about clouds. The coziest pal in the pouch.",
    favFood: "Honey toast",
    hobby: "Blanket forts",
    categories: ["animals", "cozy", "nature"],
  },
  {
    id: 4,
    name: "Miso the Cat",
    tagline: "The Window Watcher",
    image: "MIS",
    shopUrl: "https://yourshop.com/products/miso",
    color: "#f5c5a6",
    personality:
      "Miso supervises sunbeams and judges crumbs. Soft paws, softer opinions.",
    favFood: "Buttery biscuits",
    hobby: "Sunbathing",
    categories: ["animals", "cozy"],
  },
  {
    id: 5,
    name: "Rolo the Raccoon",
    tagline: "The Snack Tactician",
    image: "ROL",
    shopUrl: "https://yourshop.com/products/rolo",
    color: "#b6b3a8",
    personality:
      "Rolo is a master of midnight snacks and tiny treasures. They bring joy and exactly one extra cookie.",
    favFood: "Chocolate chips",
    hobby: "Treasure hunts",
    categories: ["animals", "food"],
  },
  {
    id: 6,
    name: "Taro the Turtle",
    tagline: "The Steady Sprinter",
    image: "TAR",
    shopUrl: "https://yourshop.com/products/taro",
    color: "#6fbf9c",
    personality:
      "Taro is slow on purpose and proud of it. They finish every race with a victory snack.",
    favFood: "Cucumber slices",
    hobby: "Gentle races",
    categories: ["animals", "sports", "nature"],
  },
  {
    id: 7,
    name: "Lumi the Axolotl",
    tagline: "The Bubble Artist",
    image: "LUM",
    shopUrl: "https://yourshop.com/products/lumi",
    color: "#f7a8b8",
    personality:
      "Lumi paints invisible art in a bubble jar and giggles at raindrops. Always glowing, always calm.",
    favFood: "Strawberry jelly",
    hobby: "Bubble making",
    categories: ["animals", "ocean", "cozy"],
  },
  {
    id: 8,
    name: "Nova the Star",
    tagline: "The Nightlight Buddy",
    image: "NOV",
    shopUrl: "https://yourshop.com/products/nova",
    color: "#8bb7ff",
    personality:
      "Nova keeps a soft glow for bedtime stories and makes wishes feel closer.",
    favFood: "Blueberry drops",
    hobby: "Wish journaling",
    categories: ["space", "cozy"],
  },
  {
    id: 9,
    name: "Orbit the Rocket",
    tagline: "The Tiny Explorer",
    image: "ORB",
    shopUrl: "https://yourshop.com/products/orbit",
    color: "#ffb56b",
    personality:
      "Orbit charts missions to the snack drawer and beyond. Always ready for launch.",
    favFood: "Caramel bites",
    hobby: "Star mapping",
    categories: ["space", "sports"],
  },
  {
    id: 10,
    name: "Nori the Whale",
    tagline: "The Soft Singer",
    image: "NOR",
    shopUrl: "https://yourshop.com/products/nori",
    color: "#7cc0d9",
    personality:
      "Nori hums tiny tunes that make teacups dance. They love hugs and ocean breezes.",
    favFood: "Sea salt taffy",
    hobby: "Humming",
    categories: ["ocean", "animals", "cozy"],
  },
  {
    id: 11,
    name: "Peb the Frog",
    tagline: "The Rain Dancer",
    image: "PEB",
    shopUrl: "https://yourshop.com/products/peb",
    color: "#85d88a",
    personality:
      "Peb celebrates puddles and collects leaf hats. Their laugh sounds like tiny bells.",
    favFood: "Mint candies",
    hobby: "Puddle hopping",
    categories: ["animals", "nature"],
  },
  {
    id: 12,
    name: "Crumble the Bear",
    tagline: "The Picnic Captain",
    image: "CRU",
    shopUrl: "https://yourshop.com/products/crumble",
    color: "#d8b08c",
    personality:
      "Crumble plans the coziest picnics and brings extra blankets for everyone.",
    favFood: "Apple pie",
    hobby: "Picnic planning",
    categories: ["animals", "food", "cozy"],
  },
  {
    id: 13,
    name: "Pico the Parrot",
    tagline: "The Story Teller",
    image: "PIC",
    shopUrl: "https://yourshop.com/products/pico",
    color: "#ffd36e",
    personality:
      "Pico collects interesting words and repeats the nice ones. A cheerful chatterbox.",
    favFood: "Pineapple rings",
    hobby: "Storytelling",
    categories: ["animals", "food"],
  },
  {
    id: 14,
    name: "Sprig the Deer",
    tagline: "The Meadow Guide",
    image: "SPR",
    shopUrl: "https://yourshop.com/products/sprig",
    color: "#c9b48a",
    personality:
      "Sprig knows every secret path in the park and shares the best spots to nap.",
    favFood: "Maple leaves",
    hobby: "Trail leading",
    categories: ["animals", "nature"],
  },
  {
    id: 15,
    name: "Gim the Gummy",
    tagline: "The Sugar Sprinter",
    image: "GIM",
    shopUrl: "https://yourshop.com/products/gim",
    color: "#ff8fb2",
    personality:
      "Gim runs on giggles and sugar sparkles. Always first to the finish line.",
    favFood: "Gummy rings",
    hobby: "Sprint races",
    categories: ["food", "sports"],
  },
  {
    id: 16,
    name: "Tilly the Tomato",
    tagline: "The Garden Coach",
    image: "TIL",
    shopUrl: "https://yourshop.com/products/tilly",
    color: "#ff6f6f",
    personality:
      "Tilly cheers for every sprout and keeps a pep talk ready for slow days.",
    favFood: "Garden salad",
    hobby: "Pep talks",
    categories: ["food", "nature"],
  },
  {
    id: 17,
    name: "Mallow the Marsh",
    tagline: "The Campfire Pal",
    image: "MAL",
    shopUrl: "https://yourshop.com/products/mallow",
    color: "#ffd6e6",
    personality:
      "Mallow is the softest friend at the fire, always ready with a warm hug.",
    favFood: "Toasted marshmallow",
    hobby: "Stargazing",
    categories: ["food", "cozy", "space"],
  },
  {
    id: 18,
    name: "Riff the Skate",
    tagline: "The Sidewalk Pro",
    image: "RIF",
    shopUrl: "https://yourshop.com/products/riff",
    color: "#78a6ff",
    personality:
      "Riff practices tiny tricks and celebrates every wobble. Big energy, small wheels.",
    favFood: "Blue raspberry pops",
    hobby: "Skate tricks",
    categories: ["sports"],
  },
  {
    id: 19,
    name: "Bean the Bunny",
    tagline: "The Gentle Gardener",
    image: "BEA",
    shopUrl: "https://yourshop.com/products/bean",
    color: "#f1c3d3",
    personality:
      "Bean plants tiny seeds and says good morning to every leaf.",
    favFood: "Carrot sticks",
    hobby: "Seed planting",
    categories: ["animals", "nature", "cozy"],
  },
  {
    id: 20,
    name: "Sora the Seahorse",
    tagline: "The Coral Keeper",
    image: "SOR",
    shopUrl: "https://yourshop.com/products/sora",
    color: "#7ed8c5",
    personality:
      "Sora collects shiny shells and keeps them in perfect rainbow order.",
    favFood: "Seaweed crisps",
    hobby: "Shell sorting",
    categories: ["ocean", "animals"],
  },
  {
    id: 21,
    name: "Zuzu the Zebra",
    tagline: "The Stripe Stylist",
    image: "ZUZ",
    shopUrl: "https://yourshop.com/products/zuzu",
    color: "#d7d3cf",
    personality:
      "Zuzu arranges patterns and helps friends find their best colors.",
    favFood: "Blackberry bites",
    hobby: "Pattern making",
    categories: ["animals", "cozy", "black"],
  },
];
